#!/usr/bin/env python3
"""Point-in-time source-lane audit. Missing evidence is explicit, never synthesized."""
from __future__ import annotations
import csv, json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MANIFEST = ROOT / "research/discovery/source_lanes.json"
OUT = ROOT / "research/discovery/source_audit.json"
DATA = ROOT / "data"


def csv_columns(path: Path) -> set[str]:
    try:
        with path.open("r", encoding="utf-8", newline="") as f:
            return {x.strip().lower() for x in (next(csv.reader(f), [])) if x.strip()}
    except (OSError, UnicodeError, csv.Error):
        return set()


def main() -> None:
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    files = [str(p.relative_to(ROOT)) for p in DATA.rglob("*") if p.is_file()] if DATA.exists() else []
    raw_columns: set[str] = set()
    schema_files = {}
    for rel in files:
        p = ROOT / rel
        if p.suffix.lower() == ".csv":
            cols = sorted(csv_columns(p))
            schema_files[rel] = cols
            raw_columns.update(cols)

    derived = set()
    if {"high", "low"}.issubset(raw_columns): derived.add("range_ratio")
    if {"open", "high", "low", "close"}.issubset(raw_columns): derived.add("close_location")
    if {"close", "volume"}.issubset(raw_columns): derived.add("volume_ratio")
    # VWAP is not present in the current OHLCV file; do not synthesize it.
    available_columns = sorted(raw_columns | derived)

    rows = []
    for lane in manifest["lanes"]:
        lane_id = lane["id"]
        if lane_id == "cex" and {"open", "high", "low", "close", "volume"}.issubset(raw_columns):
            status = "PARTIAL_DATASET"
            evidence = "OHLCV schema present; order-book/trade/execution truth absent"
        elif lane_id == "research_mining":
            status = "AVAILABLE"
            evidence = "public-source discovery artifact is generated by workflow"
        else:
            status = "UNAVAILABLE"
            evidence = "required artifacts not present in local data directory"
        rows.append({
            "id": lane_id,
            "family": lane["family"],
            "status": status,
            "evidence": evidence,
            "required_artifacts": lane["required_artifacts"],
        })

    OUT.write_text(json.dumps({
        "schema_version": 2,
        "data_files": files,
        "schema_files": schema_files,
        "raw_columns": sorted(raw_columns),
        "derived_columns": sorted(derived),
        "available_columns": available_columns,
        "lanes": rows,
    }, indent=2) + "\n", encoding="utf-8")
    print("SOURCE_AUDIT " + json.dumps({r["id"]: r["status"] for r in rows}, sort_keys=True))


if __name__ == "__main__":
    main()
